const Routes = {
  HOME_PAGE: "/",
  CGU: "/conditions-generales-vente",
  LOGIN_PAGE: "/login",
  REGISTER_PAGE: "/register",
  PROFIL_PAGE: "/profil",
  RESET_PASSWORD_PAGE: "/reset-password",
  FORGOT_PASSWORD_PAGE: "/forgot-password",
  FURNITURES_BUY_PAGE: "/achat-fournitures",
  BASKET_PAGE: "/basket",
  DELIVERY_PAGE: "/delivery",
  PAYMENT_PAGE: "/payment",
  CONFIRM_PAYMENT_PAGE: "/confirm-payment",
  CONTACT_PAGE: "/Contactez-nous",
  VOLUME_CALCULATOR_PAGE: "/volume-calculator",
  VEHICLE_RENT_PAGE: "/location-vehicules",
  ESTIMATE_DETAILS_PAGE: "/estimate/details",
  ESTIMATE_INVENTORY_PAGE: "/estimate/inventory",
  ESTIMATE_SUMMARY_PAGE: "/estimate/summary",
  ESTIMATE_VALIDATION_PAGE: "/estimate/validation",
  DASHBOARD_PAGE: "/dashboard",
  DASHBOARD_LOGIN_PAGE: "/dashboard/login",
  DASHBOARD_MOVING_PAGE: "/dashboard/moving",
  DASHBOARD_MOVING_DETAILS_PAGE: "/dashboard/moving/detail",
  DASHBOARD_MOVING_DETAILS_DENIED_PAGE: "/dashboard/moving/detail/denied",
  DASHBOARD_MOVING_DETAILS_ACCEPTED_PAGE: "/dashboard/moving/detail/accepted",
  DASHBOARD_FURNITURES_STORAGE_PAGE: "/dashboard/furnitures-storage",
  DASHBOARD_SHOP_PAGE: "/dashboard/shop",
  DASHBOARD_VEHICLE_RENTING_PAGE: "/dashboard/vehicle-renting",
  VEHICLE_RENT_PAGE_SELECTION: "/rent/vehicle/selection",
  LIFT_RENT_PAGE_SELECTION: "/rent/lift/selection",
  VEHICLE_RENT_PAGE_SUMMARY: "/rent/vehicle/summary",
  LIFT_RENT_PAGE_SUMMARY: "/rent/lift/summary",
  MOVERS_RENT_PAGE_SUMMARY: "/rent/movers/summary",
  VEHICLE_RENT_VALIDATION: "/rent/vehicle/validation",
  MOVERS_RENT_VALIDATION: "/rent/movers/validation",
  LIFT_RENT_VALIDATION: "/rent/lift/validation",
  BLOG_PAGE: "/blog",
};

export default Routes;
