name: Deploy Frontend on Heroku

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install Dependenciez
        run: npm install

      # Build the Next.js app
      - name: Build
        run: npm run build

      # Deploy to Heroku
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "bsmove-front"
          heroku_email: "developper.bsmove@gmail.com"
          buildpack: https://github.com/mars/heroku-nextjs-build.git
